### ISSUE TITLE
How to rename all file extensions to lowercase? 

### ISSUE THREAD

**Issue by sxlderek** [shenwei356/brename#29]
How to rename all file extensions to lowercase?
can someone give me an example?

**Comment by shenwei356** [comment]
Sorry, it's not supported due to the incomplete support of regular expression by [the golang standard library](https://github.com/google/re2/wiki/Syntax)




   | Escape sequences
-- | --
\lX | lowercase X (NOT SUPPORTED)
\ux | uppercase x (NOT SUPPORTED)
\L...\E | lowercase text ... (NOT SUPPORTED)
\K | reset beginning of $0 (NOT SUPPORTED)
\U...\E | upper case text ... (NOT SUPPORTED)

**Comment by shenwei356** [comment]
Sorry, it's not supported due to the incomplete support of regular expression by [the golang standard library](https://github.com/google/re2/wiki/Syntax)




   | Escape sequences
-- | --
\lX | lowercase X (NOT SUPPORTED)
\ux | uppercase x (NOT SUPPORTED)
\L...\E | lowercase text ... (NOT SUPPORTED)
\K | reset beginning of $0 (NOT SUPPORTED)
\U...\E | upper case text ... (NOT SUPPORTED)
